# 指定基础镜像 这里springboot项目运行只需要java jdk环境即可
FROM openjdk:8u201-jdk-alpine3.9

# 维护者信息
MAINTAINER RenYH <18281511768@163.com>

#挂载tmp目录
VOLUME /tmp

# 重命名
ADD target/study-1.0-SNAPSHOT.jar /app.jar

# 对外暴漏的端口号
EXPOSE 8091

# 运行
ENTRYPOINT ["java","-jar","/app.jar"]