server:
  port: 10090
  servlet:
    context-path: /mq-web

spring:
  datasource:
    # 初始化sql 脚本
    druid:
      url: jdbc:mysql://192.168.0.104:3306/raladmin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ryh123.0
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化物理连接个数
      initial-size: 5
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间(ms)
      max-wait: 60000
      # 开启缓存preparedStatement(PSCache) PSCache对支持游标的数据库性能提升巨大,比如oracle - mysql建议管理PSCache
      pool-prepared-statements: true
      # 启用PSCache后，指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      # 用来检测连接是否有效的sql
      validation-query: select 'x'
      # 申请连接时不检测连接是否有效
      test-on-borrow: false
      # 归还连接时不检测连接是否有效
      test-on-return: false
      # 申请连接时检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效（不影响性能）
      test-while-idle: true
      # 检测连接的间隔时间，若连接空闲时间 >= minEvictableIdleTimeMillis，则关闭物理连接
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间(ms)
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters（不配置则监控界面sql无法统计），监控统计filter:stat，日志filter:log4j，防御sql注入filter:wall
      filters: stat,wall
      # 支持合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql(Sql合并)功能；慢SQL记录(配置超过5秒就是慢，默认是3秒)
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      stat-view-servlet:
        # 登录druid监控web界面用户名密码
        login-username: root
        login-password: ryh123.0

  # 缓存的配置
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: -1
  redis:
    database: 0
    host: 192.168.0.104
    port: 6379
    password: ryh123.0

  # mq的配置
  rabbitmq:
    username: admin
    password: admin
    port: 5672
    addresses: 192.168.0.104
    # 开启发送失败返回
    publisher-returns: true
    # 开启发送确认
    publisher-confirm-type: correlated
    listener:
      simple:
        # 最小消费者数量
        concurrency: 2
        # 开启ack  auto manual none
        acknowledge-mode: manual
      direct:
        # 开启ack
        acknowledge-mode: manual

# mybatis plus 配置
mybatis-plus:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 属性mapper
    refresh-mapper: true
    # 驼峰下划线互转
    db-column-underline: true
  # mapper 文件
  mapper-locations: classpath:mapper/*.xml