server:
  port: 8090

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      server-addr: 120.26.198.46:8848
    gateway:
      routes:
          # 路由的ID 要求唯一
        - id: gateway_route_one
          # 匹配后提供服务的路由地址
          uri: http://localhost:8090/sayHello
          predicates:
            # 断言 路径相匹配的进行路由
            - Path=/gateway/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
