server:
  port: 8091
  servlet:
    context-path: /study-web

# springboot整合postgres连接配制
spring:
  datasource:
    url: jdbc:postgresql://172.25.9.3:5432/postgres
    username: postgres
    password: ryh123.0
    driver-class-name: org.postgresql.Driver

#mybatis-plus整合，加了表前缀的全局配制，加了类中与表中驼峰的映射，不加会查不出数据，因无法做表与类字段映射
mybatis-plus:
  type-aliases-package: org.example.ral.dao.entity
  configuration:
    map-underscore-to-camel-case: true